mppi_controller:
  ros__parameters:
    mppi:
      samples: 10000
      control_frequency: 50
      horizon: 25
      temperature: 0.5
      alpha: 0.1
    
    cost_weights:
      q_x: 2.5
      q_y: 2.5
      q_heading: 1.0
      q_vx: 0.001
      q_vy: 0.0
      q_yaw_rate: 0.0
      r_accel: 0.001
      r_steering: 0.001

    visualization:
      enable_viz: true
      top_k_paths: 10
      line_width: 0.05
      path_alpha: 0.7